name: Update Default Mold Version

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  check-update-mold-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update action.yml if needed
        run: |
          set -x
          curl -s https://api.github.com/repos/rui314/mold/releases/latest > info
          RELEASE_TAG=$(jq -r .tag_name info | sed 's/^v//')
          RELEASE_DATE=$(jq -r .published_at info)
          CURRENT_TAG=$(grep default: action.yml | head -1 | cut -d "'" -f 2)

          echo "$RELEASE_TAG" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'

          if [ $CURRENT_TAG = $RELEASE_TAG ]; then
            echo "action.yml is already up to date"
          elif [ $(date +%s) -lt $(date -d "$RELEASE_DATE + 7 days" +%s) ]; then
            echo "still in grace period"
          else
            sed -i "s/default: '.*'/default: '$RELEASE_TAG'/" action.yml
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -am "Update default version to $RELEASE_TAG"
            git push
            git tag -f v1
            git push -f --tags
          fi
